### ISSUE TITLE
Not really an issue, but rather a question regarding installation

### ISSUE THREAD

**Issue by jwchoi09** [lbfs/DeepFaceLab_Linux#26]
I am currently attempting to install deepfacelab on ubuntu in my cuda enabled machine.
I also looked at centos version by @elemantalcode and had a few questions.
1. If installing through Anaconda (virtual environment) as in your guide, 
do we not need to download NVIDIA driver, git, ffmpeg, etc through apt-get? 

2. Also, could you briefly guide me through the installation process as if I were to install it in ubuntu without Anaconda? ex) prerequisite libraries to install

Thanks in advance.

**Comment by lbfs** [comment]
You are correct in the fact that you need FFMpeg, Git, and the NVIDIA driver to run this project. You can pull some of these through Anaconda or your system package manager, but they must be installed. 

I'm afraid I won't be able to tell you how to install it natively on Ubuntu as that is something I am not currently focused on supporting. Installing NVIDIA's libraries natively is not worth it due to interlocking dependencies, can be hard to prune from the system, and is much more difficult to get working. 

However, I can link you to the old installation instructions for Ubuntu 16.04 using CUDA 9 for the older version of DFL. https://raw.githubusercontent.com/lbfs/DeepFaceLab_Linux/6ed10e5de6ff59f4fbd7ff27b715c50b595ff027/ubuntu16.04-cuda9-installer.sh

This should be only ran on a fresh install of Ubuntu, but should give you an idea of what needs to be done. Tensorflow only supports CUDA 10 and higher now, and while DeepFaceLab on Windows uses Cuda 9.2, Tensorflow needs to be recompiled to use it as that is not the version in the package manager. 

I hope this helps.

https://raw.githubusercontent.com/lbfs/DeepFaceLab_Linux/6ed10e5de6ff59f4fbd7ff27b715c50b595ff027/ubuntu16.04-cuda9-installer.sh

**Comment by jwchoi09** [comment]
Wow thank you for such clear details.
I appreciate it!
