### ISSUE TITLE
View the preview in a server environment without a monitor

### ISSUE THREAD

**Issue by btx000** [lbfs/DeepFaceLab_Linux#3]
I use this software in juputerlab environment.
Its only have a terminal so that can't show a preview.
I think  use cv2.imwrite( ) to write the preview pic into the workspace can solve this problem.

**Comment by lbfs** [comment]
@btx000 If you turn on "write preview history" and look at the directory under workspace/model/MODELNAME_history I believe the previews should be there, is this what you're looking for?

**Comment by btx000** [comment]
I mean, I can't see the preview results immediately in no preview mode, it's going to wait 15 minutes.

Can we see the preview results in other ways at any time? @lbfs

**Comment by btx000** [comment]
Using the original method of saving preview history generates a lot of pictures, which takes up a lot of disk space on my Aliyun PAI platform with only 5GB available space, and hanging up for a long time can cause crashes. I just want to take a look at it when I want to see a preview.

**Comment by lbfs** [comment]
I might be able to look into creating a way of limiting the amount of saved images so that if it hits a certain point it deletes older preview images. 

You do bring an interesting point about viewing the preview results whenever we desire, I think that could be an interesting feature, but I'm not sure about the best way about going about handling that.

I'm currently busy with school so it may be a week or so before I have time to try to implement this fully. Although, I do think this is a neat idea that requires more exploring.

**Comment by btx000** [comment]
Thank you for your porting on Linux to make it possible for me to run programs on Aliyun PAI.

Another problem with the use of scripts is that the name of the .sh script uses a space, which requires the "\" escape character when the terminal input is executed. I think it's a better choice to replace the space in the file name with "_".

**Comment by lbfs** [comment]
Scripts have been renamed.

**Comment by lbfs** [comment]
You can now limit your preview history during the model override settings. Any numeric value will set the max cap of how many files can be in the history directory.
